jobsearchtracker: Applicant config check OK!
server:
  port: 8080
spring:
  application:
    name: applicant
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        currentSessionContextClass: org.springframework.orm.hibernate5.SpringSessionContext
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
