server:
  port: 8080
spring:
  profiles:
    active: default
  application:
    name: applicant
  config:
    import: optional:configserver:http://config:8889
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        currentSessionContextClass: org.springframework.orm.hibernate5.SpringSessionContext
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
#      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
